### ISSUE TITLE
police job ammo error

### ISSUE THREAD

**Issue by Andyauk** [qbcore-redm-framework/qbr-policejob#16]
`SCRIPT ERROR: @qbr-policejob/client/job.lua:208: attempt to index a nil value (field '?')^7`

I keep getting this error. and I cant work out how to fix it, from a fresh instill too as a test. 

seems to be to do with trying to find weaponAmmoLabel

**Comment by gononono64** [comment]
`208: local StationBlip = N_0x554d9d53f696d002(1664425300, v.coords)`
N_0x554d9d53f696d002 is not a valid functIon call. Replace line 208 with:
`local StationBlip = Citizen.InvokeNative(0x554d9d53f696d002, 1664425300, v.coords)`
ill update this tmr

**Comment by Andyauk** [comment]
> `208: local StationBlip = N_0x554d9d53f696d002(1664425300, v.coords)` N_0x554d9d53f696d002 is not a valid functIon call. Replace line 208 with: `local StationBlip = Citizen.InvokeNative(0x554d9d53f696d002, 1664425300, v.coords)` ill update this tmr

nice find, but I guess you have the commented out DrawText3D in still, i removed that. in that case it would be 223, un changed script.
 
`^1SCRIPT ERROR: @qbr-policejob/client/job.lua:223: attempt to index a nil value (field '?')^7`

all to do with weaponAmmoLabel
